# Generated by Django 5.1.1 on 2025-04-29 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('jenis_hewan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.jenishewan')),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hewan', to='main.klien')),
            ],
            options={
                'ordering': ['pemilik__nama', 'jenis_hewan__nama', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='main.hewan')),
            ],
            options={
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
