# Generated by Django 5.1.1 on 2025-04-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_klien_hewan_kunjungan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hewan',
            name='jenis_hewan',
        ),
        migrations.RemoveField(
            model_name='hewan',
            name='pemilik',
        ),
        migrations.RemoveField(
            model_name='kunjungan',
            name='hewan',
        ),
        migrations.DeleteModel(
            name='JenisHewan',
        ),
        migrations.DeleteModel(
            name='Klien',
        ),
        migrations.DeleteModel(
            name='Hewan',
        ),
        migrations.DeleteModel(
            name='Kunjungan',
        ),
    ]
