# Generated by Django 5.1.7 on 2025-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_remove_hewan_jenis_hewan_remove_hewan_pemilik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokterHewan',
            fields=[
                ('no_dokter_hewan', models.UUIDField(primary_key=True, serialize=False)),
                ('no_tenaga_medis', models.UUIDField()),
            ],
            options={
                'db_table': 'pet_clinic"."DOKTER_HEWAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrontDesk',
            fields=[
                ('no_front_desk', models.UUIDField(primary_key=True, serialize=False)),
                ('no_pegawai', models.UUIDField()),
            ],
            options={
                'db_table': 'pet_clinic"."FRONT_DESK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no_identitas_klien', models.UUIDField()),
                ('tanggal_lahir', models.DateField()),
                ('id_jenis', models.UUIDField()),
                ('url_foto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pet_clinic"."HEWAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('no_identitas_klien', models.UUIDField(primary_key=True, serialize=False)),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pet_clinic"."INDIVIDU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisHewan',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pet_clinic"."JENIS_HEWAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klien',
            fields=[
                ('no_identitas', models.UUIDField(primary_key=True, serialize=False)),
                ('tanggal_registrasi', models.DateField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pet_clinic"."KLIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.UUIDField(primary_key=True, serialize=False)),
                ('nama_hewan', models.CharField(max_length=50)),
                ('no_identitas_klien', models.UUIDField()),
                ('no_front_desk', models.UUIDField()),
                ('no_perawat_hewan', models.UUIDField()),
                ('no_dokter_hewan', models.UUIDField()),
                ('kode_vaksin', models.CharField(blank=True, max_length=6, null=True)),
                ('tipe_kunjungan', models.CharField(max_length=10)),
                ('timestamp_awal', models.DateTimeField()),
                ('timestamp_akhir', models.DateTimeField(blank=True, null=True)),
                ('suhu', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pet_clinic"."KUNJUNGAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KunjunganKeperawatan',
            fields=[
                ('id_kunjungan', models.UUIDField()),
                ('nama_hewan', models.CharField(max_length=50)),
                ('no_identitas_klien', models.UUIDField()),
                ('no_front_desk', models.UUIDField()),
                ('no_perawat_hewan', models.UUIDField()),
                ('no_dokter_hewan', models.UUIDField()),
                ('kode_perawatan', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pet_clinic"."KUNJUNGAN_KEPERAWATAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('dosis', models.TextField()),
            ],
            options={
                'db_table': 'pet_clinic"."OBAT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('no_pegawai', models.UUIDField(primary_key=True, serialize=False)),
                ('tanggal_mulai_kerja', models.DateField()),
                ('tanggal_akhir_kerja', models.DateField(blank=True, null=True)),
                ('email_user', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pet_clinic"."PEGAWAI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('kode_perawatan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_perawatan', models.CharField(max_length=100)),
                ('biaya_perawatan', models.IntegerField()),
            ],
            options={
                'db_table': 'pet_clinic"."PERAWATAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerawatHewan',
            fields=[
                ('no_perawat_hewan', models.UUIDField(primary_key=True, serialize=False)),
                ('no_tenaga_medis', models.UUIDField()),
            ],
            options={
                'db_table': 'pet_clinic"."PERAWAT_HEWAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('no_identitas_klien', models.UUIDField(primary_key=True, serialize=False)),
                ('nama_perusahaan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pet_clinic"."PERUSAHAAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenagaMedis',
            fields=[
                ('no_tenaga_medis', models.UUIDField(primary_key=True, serialize=False)),
                ('no_pegawai', models.UUIDField()),
                ('no_izin_praktik', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'pet_clinic"."TENAGA_MEDIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'pet_clinic"."USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('kode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
            ],
            options={
                'db_table': 'pet_clinic"."VAKSIN',
                'managed': False,
            },
        ),
    ]
